name: Deploy Terraform to GCP

on:
  workflow_dispatch:

jobs:
  deploy:
    uses: k-candidate/gha-workflows/.github/workflows/deployment-pipeline.yaml@main
    with:
      region: "us-east1"      
      terraform_directory: "."
      project_id: 'qwiklabs-gcp-01-0b750d7737a2'
    secrets:
      service_account_key: ${{ secrets.GCP_SA_KEY }}
