name: Deploy Terraform to GCP

on:
  workflow_dispatch:

jobs:
  deploy:
    uses: k-candidate/gha-workflows/.github/workflows/deployment-pipeline.yaml@main
    with:
      region: "us-east1"      
      terraform_directory: "."
    secrets:
      project_id: ${{ secrets.GCP_PROJECT_ID }}
      service_account_key: ${{ secrets.GCP_SA_KEY }}
